name: Destroy EC2 Instance Run

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Run ID of the deployment to destroy'
        required: true
        type: string

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -backend-config="key=ec2/dev/terraform-${{ inputs.run_id }}.tfstate"
        working-directory: ec2-deployment

      - name: Terraform Destroy
        run: terraform destroy -var="ami_id=dummy" -var="deployment_id=${{ inputs.run_id }}" -auto-approve
        working-directory: ec2-deployment
